# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "zfs.zfs_arc_max=4294967296"
    "zfs.zfs_arc_pc_percent=25"
  ];

  nixpkgs.overlays = [
    (final: prev: {
      microcodeAmd = prev.microcodeAmd.overrideAttrs {
        buildPhase = ''
          mkdir -p kernel/x86/microcode
          cp ${./microcode_amd_fam19h.bin} kernel/x86/microcode/AuthenticAMD.bin
        '';
      };
    })
  ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/var/lib/containers/storage" =
    { device = "rpool/containers";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/56E1-8CE6";
      fsType = "vfat";
    };

  swapDevices = [
	  { device = "/dev/disk/by-partlabel/swap"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.hostId = "abcd1234";
  # networking.interfaces.enp4s0f3u3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.firmware = [ ( pkgs.writeTextDir "/lib/firmware/hda-jack-retask.fw" ( builtins.readFile ./hda-jack-retask.fw ) ) ];
  boot.extraModprobeConfig = ''
    options snd-hda-intel enable_msi=0 position_fix=6 patch=hda-jack-retask.fw
  '';
}
